### ISSUE TITLE
Aircraft detected in zero - something related to Datasource

### ISSUE THREAD

**Issue by tech4solitude** [Ysurac/FlightAirMap#409]
I've installed the FlightAirMap with Nginx - MySQL and it works. But its showing aircraft detected as Zero 
However i've script run daemon-acars.php 

I've followed the installation steps - Please note I was not able to setup init scripts

systemctl daemon-reload
systemctl enable flightairmap.service
systemctl start flightairmap.service
 
since i was getting flightairmap not found error 
Please advice on the fixes

**Comment by Ysurac** [comment]
You use ACARS as datasource ? Do you have some output when run the script ?

For init scripts you copied them to the /lib/systemd/... path and fixed the path if you don't use the default one (/var/www/flightarimap/) ?

**Comment by tech4solitude** [comment]
Hi @Ysurac  thanks for the quick reply 

I use ACARS for datasource - please check the screen shot 
for init scripts.. I copied the files to /etc/systemd/flightairmap.service
and edited like this 
[Unit]
Description=FlightAirMap

[Service]
ExecStartPre=/bin/sleep 30
ExecStart=/var/www/flightairmap/scripts/daemon-spotter.php

[Install]
WantedBy=multi-user.target

Please advice on the same

**Comment by Ysurac** [comment]
What output do you have when you run daemon-acars.php or daemon-spotter.php manually ?

**Comment by tech4solitude** [comment]
I'm getting following error 
when i run -  php daemon-acars.php

Can't calculate geoid, check that you downloaded it via update_db.php (Exception: /var/www/flightairmap/require/../data/egm2008-1.pgm doesn't exist in /var/www/flightairmap/require/class.GeoidHeight.php:46
Stack trace:
#0 /var/www/flightairmap/require/class.SpotterImport.php(60): GeoidHeight->__construct()
#1 /var/www/flightairmap/require/class.ACARS.php(30): SpotterImport->__construct(Object(PDO))
#2 /var/www/flightairmap/scripts/daemon-acars.php(26): ACARS->__construct(NULL, true)
#3 {main})
Listen to acarsdec ... PHP Warning:  socket_bind(): unable to bind address [98]: Address already in use in /var/www/flightairmap/scripts/daemon-acars.php on line 45

**Comment by Ysurac** [comment]
Did you run update_db.php ?
daemon-acars.php is a UDP server for acarsdec/acarsdeco, it listen on a port (that is already used in this case). If it's not what you want, run daemon-spotter.php that can be used for ACARS SBS-3 over TCP, ACARS from acarsdec json (TCP and UDP).

**Comment by tech4solitude** [comment]
I did run update_db.php by php update_db.php 
When I run php daemon-spotter.php - i'm getting following error 

Connecting...
Connect to all...
Connection in progress to 127.0.0.1:3306 (sbs)....
SCAN MODE

Wrong line format. Ignoring...
[Reconnect after an error...
Connect to all...
Connection in progress to 127.0.0.1:3306 (sbs)....
Check all...
Update last seen flights data...


FYI I'm using nginx - mysql - php combination 
also please check the screenshot of output :  netstat -tulpn
<img width="550" alt="screenshot 2018-07-18 at 11 14 38 pm" src="https://user-images.githubusercontent.com/13044958/42898324-75ede11a-8ae0-11e8-9947-10f51d1bb4cc.png">

**Comment by Ysurac** [comment]
What program do you use for ACARS ?

**Comment by tech4solitude** [comment]
@Ysurac  anything on this

**Comment by Ysurac** [comment]
For FlightAirMap, you need to have a source, I don't provide any by default. What is your source and what you want to do ?

**Comment by tech4solitude** [comment]
Oh ok - I just wanted to try this for real time aircraft tracking - just like in your example (https://real.flightairmap.com/) 
Can you please suggest be some source or any ways to integrate it

**Comment by Ysurac** [comment]
For real flight there is adsbexchange or adsbhub. Else you can use a RTL-SDR USB key with Dump1090 like the key available here: https://www.rtl-sdr.com/buy-rtl-sdr-dvb-t-dongles/ then you will get flights that are near your position.

**Comment by tech4solitude** [comment]
@Ysurac  Thank you. Can you please help us in how to use  adsbexchange or adsbhub or any other source for showing real aircraft. We tried couple of times - but not able to figure out
